### ISSUE TITLE
说明书打不开了

### ISSUE THREAD

**Issue by Hew007** [poormonitor/MyUNIV#2]
请教这个如何使用，谢谢

**Comment by poormonitor** [comment]
感谢您选择 MyUNIV。
若是想直接体验服务，您可访问 univ.techo.cool 或微信搜索小程序 MyUNIV 进行体验。
当前系统有两个分支，legacy分支使用 Flask + Bootstrap，master分支使用 FastAPI + Vue3，相关的 README 已经更新。
